services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8013:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    links:
      - db
  db:
    container_name: mysql_iaw
    image: mariadb:10.4.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_iaw:/var/lib/mysql
  apache:
    container_name: gabinete
    build: .
    restart: always
    ports:
      - 8012:80
    volumes:
      - ./htdocs:/var/www/html
      - ./config.ini:/var/www/config.ini
      - apache-config:/etc/apache2
volumes:
  db_iaw:
  apache-config:
